//! The freedesktop launcher entry: a `.desktop` file and hicolor icons under
//! `$XDG_DATA_HOME`, so the app appears in the applications list and the dock
//! shows its icon. The GUI installs it; `callboard uninstall` removes it.
use crate::{Error, lifecycle::Paths};
use std::{
    io::Write,
    path::{Path, PathBuf},
};

const MARKER: &str = "# Generated by callboard-gui --install-desktop\n";
/// Matches the GUI's Wayland app_id and X11 WM_CLASS, which is how a dock
/// pairs a running window with this entry.
pub const APP_ID: &str = "callboard";

/// One bundled icon: its hicolor size directory (`64x64`, `scalable`) and bytes.
pub struct Icon {
    pub size: &'static str,
    pub bytes: &'static [u8],
}

fn data_home(paths: &Paths) -> &Path {
    paths.data_dir().parent().unwrap()
}

pub fn entry_path(paths: &Paths) -> PathBuf {
    data_home(paths).join(format!("applications/{APP_ID}.desktop"))
}

fn icon_theme(paths: &Paths) -> PathBuf {
    data_home(paths).join("icons/hicolor")
}

fn icon_path(paths: &Paths, size: &str) -> PathBuf {
    let extension = if size == "scalable" { "svg" } else { "png" };
    icon_theme(paths).join(format!("{size}/apps/{APP_ID}.{extension}"))
}

/// The icon sizes [`remove`] cleans up; the GUI's bundled set.
pub const SIZES: [&str; 7] = [
    "16x16", "32x32", "64x64", "128x128", "256x256", "512x512", "scalable",
];

/// Quote one Exec argument per the Desktop Entry spec: reserved characters
/// are backslash-escaped inside double quotes, then the value as a whole
/// escapes backslashes again, and `%` is doubled so it is not a field code.
fn quote_exec(value: &str) -> Result<String, Error> {
    if value.chars().any(char::is_control) {
        return Err("desktop entry values cannot contain control characters".into());
    }
    let mut quoted = String::from("\"");
    for c in value.chars() {
        match c {
            '"' | '`' | '$' => quoted.extend(['\\', c]),
            '\\' => quoted.push_str("\\\\\\\\"),
            '%' => quoted.push_str("%%"),
            c => quoted.push(c),
        }
    }
    quoted.push('"');
    Ok(quoted)
}

/// The entry launches `executable` by absolute path: a desktop session's
/// launcher often lacks `~/.cargo/bin` on its PATH.
pub fn render(executable: &Path) -> Result<String, Error> {
    if !executable.is_absolute() {
        return Err("the GUI executable must be absolute".into());
    }
    let exec = quote_exec(
        executable
            .to_str()
            .ok_or("desktop entry paths must be UTF-8")?,
    )?;
    Ok(format!(
        "[Desktop Entry]\n{MARKER}Type=Application\nName=Callboard\n\
         Comment=Per-user bulletin board for feeds, todos, and notes\n\
         Exec={exec}\nIcon={APP_ID}\nTerminal=false\nCategories=Utility;\n\
         Keywords=feeds;todo;notes;board;\nStartupNotify=true\nStartupWMClass={APP_ID}\n"
    ))
}

/// What occupies [`entry_path`].
pub enum Entry {
    Absent,
    Generated,
    /// Someone else's entry, which is never replaced or removed.
    Custom,
}

pub fn read_entry(paths: &Paths) -> Result<Entry, Error> {
    match std::fs::read_to_string(entry_path(paths)) {
        Ok(text) if text.contains(MARKER) => Ok(Entry::Generated),
        Ok(_) => Ok(Entry::Custom),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Entry::Absent),
        // Unreadable or not UTF-8: not ours.
        Err(_) => Ok(Entry::Custom),
    }
}

/// Write the icons, then the entry atomically, so a launcher watching the
/// directory never sees an entry whose icon is missing. Returns the entry path.
pub fn install(paths: &Paths, executable: &Path, icons: &[Icon]) -> Result<PathBuf, Error> {
    let entry = render(executable)?;
    let target = entry_path(paths);
    if let Entry::Custom = read_entry(paths)? {
        return Err(format!(
            "refusing to replace {}: not one callboard-gui installed",
            target.display()
        )
        .into());
    }
    for icon in icons {
        let path = icon_path(paths, icon.size);
        std::fs::create_dir_all(path.parent().unwrap())?;
        std::fs::write(&path, icon.bytes)?;
    }
    refresh_icon_cache(paths);
    let dir = target.parent().unwrap();
    std::fs::create_dir_all(dir)?;
    let mut temp = tempfile::NamedTempFile::new_in(dir)?;
    temp.write_all(entry.as_bytes())?;
    temp.as_file().sync_all()?;
    // Entries are conventionally world-readable; the tempfile default is 0600.
    use std::os::unix::fs::PermissionsExt;
    temp.as_file()
        .set_permissions(std::fs::Permissions::from_mode(0o644))?;
    temp.persist(&target)?;
    Ok(target)
}

/// Delete the generated entry and its icons. Returns the removed entry, or
/// `None` when there was none to remove; a custom entry and its icons are left.
pub fn remove(paths: &Paths) -> Result<Option<PathBuf>, Error> {
    let target = entry_path(paths);
    match read_entry(paths)? {
        Entry::Generated => (),
        Entry::Absent | Entry::Custom => return Ok(None),
    }
    std::fs::remove_file(&target)?;
    for size in SIZES {
        match std::fs::remove_file(icon_path(paths, size)) {
            Err(e) if e.kind() != std::io::ErrorKind::NotFound => return Err(e.into()),
            _ => (),
        }
    }
    refresh_icon_cache(paths);
    Ok(Some(target))
}

/// GTK trusts an existing `icon-theme.cache` over the directory, so a stale
/// one hides new icons and keeps removed ones. Without a cache there is
/// nothing to do. Best effort: the tool may be absent.
fn refresh_icon_cache(paths: &Paths) {
    let theme = icon_theme(paths);
    if theme.join("icon-theme.cache").exists() {
        let _ = std::process::Command::new("gtk-update-icon-cache")
            .args(["-f", "-t", "-q"])
            .arg(&theme)
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lifecycle::Environment;

    fn paths(root: &Path) -> Paths {
        Paths::resolve(&Environment {
            home: Some(root.to_path_buf()),
            data_home: Some(root.join("data")),
            config_home: Some(root.join("config")),
            socket_dir: Some(root.join("run")),
            ..Default::default()
        })
        .unwrap()
    }

    #[test]
    fn exec_quoting_escapes_reserved_characters_and_rejects_newlines() {
        assert_eq!(quote_exec("/a b/c").unwrap(), "\"/a b/c\"");
        assert_eq!(
            quote_exec("/x\"$`%\\y").unwrap(),
            "\"/x\\\"\\$\\`%%\\\\\\\\y\""
        );
        assert!(quote_exec("/x\nExec=evil").is_err());
        assert!(render(Path::new("relative")).is_err());
    }

    #[test]
    fn install_and_remove_round_trip_and_spare_custom_entries() {
        let root = tempfile::tempdir().unwrap();
        let paths = paths(root.path());
        let icons = [
            Icon {
                size: "64x64",
                bytes: b"png",
            },
            Icon {
                size: "scalable",
                bytes: b"<svg/>",
            },
        ];
        let entry = install(&paths, Path::new("/opt/callboard-gui"), &icons).unwrap();
        assert_eq!(
            entry,
            root.path().join("data/applications/callboard.desktop")
        );
        let text = std::fs::read_to_string(&entry).unwrap();
        assert!(text.contains("Exec=\"/opt/callboard-gui\"\n"));
        let svg = root
            .path()
            .join("data/icons/hicolor/scalable/apps/callboard.svg");
        assert_eq!(std::fs::read(&svg).unwrap(), b"<svg/>");
        // Reinstalling replaces our own entry.
        install(&paths, Path::new("/opt/callboard-gui"), &icons).unwrap();

        assert_eq!(remove(&paths).unwrap(), Some(entry.clone()));
        assert!(!entry.exists() && !svg.exists());
        assert_eq!(remove(&paths).unwrap(), None);

        std::fs::write(&entry, "[Desktop Entry]\nName=Mine\n").unwrap();
        assert!(install(&paths, Path::new("/opt/callboard-gui"), &icons).is_err());
        assert_eq!(remove(&paths).unwrap(), None);
        assert!(entry.exists());
    }
}
