//! Render and install a systemd user unit; installation does not stop a running service.
use crate::{
    Error,
    lifecycle::{Paths, check_shared_directory, private_file},
};
use std::{
    io::Write,
    os::unix::fs::{MetadataExt, PermissionsExt},
    path::Path,
};
const MARKER: &str = "# Generated by callboard setup\n";

fn quote(value: &str, exec: bool) -> Result<String, Error> {
    if value.chars().any(char::is_control) {
        return Err("systemd values cannot contain control characters".into());
    }
    let mut value = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('%', "%%");
    if exec {
        value = value.replace('$', "$$");
    }
    Ok(format!("\"{value}\""))
}
fn text(path: &Path) -> Result<&str, Error> {
    path.to_str()
        .ok_or_else(|| "systemd paths must be UTF-8".into())
}

pub fn render(paths: &Paths, executable: &Path) -> Result<String, Error> {
    if !executable.is_absolute() {
        return Err("service executable must be absolute".into());
    }
    let mut unit = format!(
        "{MARKER}[Unit]\nDescription=Callboard per-user bulletin board\n\n[Service]\nType=exec\nExecStart={} serve\nRestart=on-failure\nRestartSec=2\nTimeoutStopSec=10\nUMask=0077\n",
        quote(text(executable)?, true)?
    );
    for (name, path) in [
        ("XDG_DATA_HOME", paths.data_dir().parent().unwrap()),
        ("XDG_CONFIG_HOME", paths.config_dir().parent().unwrap()),
        ("CALLBOARD_SOCKET_DIR", paths.socket_dir()),
    ] {
        unit.push_str(&format!(
            "Environment={}\n",
            quote(&format!("{name}={}", text(path)?), false)?
        ));
    }
    unit.push_str("\n[Install]\nWantedBy=default.target\n");
    Ok(unit)
}

/// Where setup writes the unit: the systemd user directory beside our config.
pub fn unit_path(paths: &Paths) -> std::path::PathBuf {
    paths
        .config_dir()
        .parent()
        .unwrap()
        .join("systemd/user/callboard.service")
}

/// What occupies [`unit_path`].
pub enum Unit {
    Absent,
    /// Written by setup; the contents.
    Generated(String),
    /// A hand-written unit, which setup never replaces or removes.
    Custom,
}

pub fn read_unit(paths: &Paths) -> Result<Unit, Error> {
    let target = unit_path(paths);
    match std::fs::symlink_metadata(&target) {
        // Setup writes a private regular file. Anything else there is
        // someone else's: a hand-written unit is commonly 0644 or a symlink.
        Ok(metadata)
            if metadata.is_file()
                && metadata.mode() & 0o777 == 0o600
                && metadata.uid() == rustix::process::geteuid().as_raw() =>
        {
            let mut file = private_file(&target, rustix::process::geteuid().as_raw())?;
            let mut old = String::new();
            use std::io::Read;
            (&mut file).take(1024 * 1024).read_to_string(&mut old)?;
            Ok(if old.starts_with(MARKER) {
                Unit::Generated(old)
            } else {
                Unit::Custom
            })
        }
        Ok(_) => Ok(Unit::Custom),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Unit::Absent),
        Err(e) => Err(e.into()),
    }
}

async fn systemctl(args: &[&str]) -> Result<std::process::Output, Error> {
    Ok(tokio::time::timeout(
        std::time::Duration::from_secs(15),
        tokio::process::Command::new("systemctl")
            .arg("--user")
            .args(args)
            .stdin(std::process::Stdio::null())
            .kill_on_drop(true)
            .output(),
    )
    .await??)
}

async fn systemctl_ok(args: &[&str], context: &str) -> Result<(), Error> {
    let output = systemctl(args).await?;
    if !output.status.success() {
        return Err(format!(
            "{context}; systemctl --user {} failed: {} {}",
            args.join(" "),
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        )
        .into());
    }
    Ok(())
}

/// Write atomically and refuse to overwrite a hand-written unit. Enable it for
/// future user-manager starts; do not seize a running on-demand service's lock.
pub async fn install(paths: &Paths, executable: &Path) -> Result<std::path::PathBuf, Error> {
    let unit = render(paths, executable)?;
    let target = unit_path(paths);
    let dir = target.parent().unwrap();
    check_shared_directory(dir, rustix::process::geteuid().as_raw())?;
    if let Unit::Custom = read_unit(paths)? {
        return Err("refusing to replace a custom callboard.service".into());
    }
    let mut temp = tempfile::NamedTempFile::new_in(dir)?;
    temp.as_file()
        .set_permissions(std::fs::Permissions::from_mode(0o600))?;
    temp.write_all(unit.as_bytes())?;
    temp.as_file().sync_all()?;
    temp.persist(&target)?;
    let context = format!("unit written to {}", target.display());
    systemctl_ok(&["daemon-reload"], &context).await?;
    systemctl_ok(&["enable", "callboard.service"], &context).await?;
    Ok(target)
}

/// Disable and delete the generated unit. `stop` also stops a service it
/// runs; otherwise a running service keeps running. Returns the removed path,
/// or `None` when there was no unit. Refuses a custom unit.
pub async fn remove(paths: &Paths, stop: bool) -> Result<Option<std::path::PathBuf>, Error> {
    let target = unit_path(paths);
    match read_unit(paths)? {
        Unit::Absent => return Ok(None),
        Unit::Custom => {
            return Err(format!(
                "{} is a custom unit, not one setup generated; disable and remove it yourself",
                target.display()
            )
            .into());
        }
        Unit::Generated(_) => (),
    }
    let mut disable = vec!["disable"];
    if stop {
        disable.push("--now");
    }
    disable.push("callboard.service");
    systemctl_ok(&disable, "nothing removed").await?;
    std::fs::remove_file(&target)?;
    systemctl_ok(&["daemon-reload"], &format!("removed {}", target.display())).await?;
    Ok(Some(target))
}

/// `setup --status`: the unit file and what systemd says about it.
pub async fn status(paths: &Paths) -> Result<String, Error> {
    let target = unit_path(paths);
    let contents = match read_unit(paths)? {
        Unit::Absent => {
            return Ok(format!(
                "No unit at {}; the service starts on demand. `callboard setup` installs one.\n",
                target.display()
            ));
        }
        Unit::Custom => {
            return Ok(format!(
                "{} is a custom unit (not generated by setup).\n",
                target.display()
            ));
        }
        Unit::Generated(contents) => contents,
    };
    let query = async |verb: &str| match systemctl(&[verb, "callboard.service"]).await {
        // These verbs print the state even when they exit nonzero.
        Ok(output) => String::from_utf8_lossy(&output.stdout).trim().to_owned(),
        Err(e) => format!("unknown ({e})"),
    };
    let executable = contents
        .lines()
        .find_map(|line| line.strip_prefix("ExecStart="))
        .unwrap_or("?");
    Ok(format!(
        "Unit: {} (generated by setup)\nEnabled: {}\nActive: {}\nExecStart: {executable}\n",
        target.display(),
        query("is-enabled").await,
        query("is-active").await,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn systemd_quoting_preserves_literals_and_rejects_line_injection() {
        assert_eq!(
            quote("/a b/$x%q\\\"", true).unwrap(),
            "\"/a b/$$x%%q\\\\\\\"\""
        );
        assert_eq!(quote("KEY=$x%q", false).unwrap(), "\"KEY=$x%%q\"");
        assert!(quote("x\nExecStart=evil", true).is_err());
    }
}
