//! Render and install a systemd user unit; installation does not stop a running service.
use crate::{
    Error,
    lifecycle::{Paths, check_shared_directory, private_file},
};
use std::{io::Write, os::unix::fs::PermissionsExt, path::Path};
const MARKER: &str = "# Generated by callboard setup\n";

fn quote(value: &str, exec: bool) -> Result<String, Error> {
    if value.chars().any(char::is_control) {
        return Err("systemd values cannot contain control characters".into());
    }
    let mut value = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('%', "%%");
    if exec {
        value = value.replace('$', "$$");
    }
    Ok(format!("\"{value}\""))
}
fn text(path: &Path) -> Result<&str, Error> {
    path.to_str()
        .ok_or_else(|| "systemd paths must be UTF-8".into())
}

pub fn render(paths: &Paths, executable: &Path) -> Result<String, Error> {
    if !executable.is_absolute() {
        return Err("service executable must be absolute".into());
    }
    let mut unit = format!(
        "{MARKER}[Unit]\nDescription=Callboard per-user bulletin board\n\n[Service]\nType=exec\nExecStart={} serve\nRestart=on-failure\nRestartSec=2\nTimeoutStopSec=10\nUMask=0077\n",
        quote(text(executable)?, true)?
    );
    for (name, path) in [
        ("XDG_DATA_HOME", paths.data_dir().parent().unwrap()),
        ("XDG_CONFIG_HOME", paths.config_dir().parent().unwrap()),
        ("CALLBOARD_SOCKET_DIR", paths.socket_dir()),
    ] {
        unit.push_str(&format!(
            "Environment={}\n",
            quote(&format!("{name}={}", text(path)?), false)?
        ));
    }
    unit.push_str("\n[Install]\nWantedBy=default.target\n");
    Ok(unit)
}

/// Write atomically and refuse to overwrite a hand-written unit. Enable it for
/// future user-manager starts; do not seize a running on-demand service's lock.
pub async fn install(paths: &Paths, executable: &Path) -> Result<std::path::PathBuf, Error> {
    let unit = render(paths, executable)?;
    let dir = paths.config_dir().parent().unwrap().join("systemd/user");
    check_shared_directory(&dir, rustix::process::geteuid().as_raw())?;
    let target = dir.join("callboard.service");
    match std::fs::symlink_metadata(&target) {
        Ok(_) => {
            let mut file = private_file(&target, rustix::process::geteuid().as_raw())?;
            let mut old = String::new();
            use std::io::Read;
            (&mut file).take(1024 * 1024).read_to_string(&mut old)?;
            if !old.starts_with(MARKER) {
                return Err("refusing to replace a custom callboard.service".into());
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => (),
        Err(e) => return Err(e.into()),
    }
    let mut temp = tempfile::NamedTempFile::new_in(&dir)?;
    temp.as_file()
        .set_permissions(std::fs::Permissions::from_mode(0o600))?;
    temp.write_all(unit.as_bytes())?;
    temp.as_file().sync_all()?;
    temp.persist(&target)?;
    for args in [
        &["--user", "daemon-reload"][..],
        &["--user", "enable", "callboard.service"][..],
    ] {
        let status = tokio::time::timeout(
            std::time::Duration::from_secs(15),
            tokio::process::Command::new("systemctl")
                .args(args)
                .kill_on_drop(true)
                .status(),
        )
        .await??;
        if !status.success() {
            return Err(format!(
                "unit written to {}; systemctl {} failed: {status}",
                target.display(),
                args.join(" ")
            )
            .into());
        }
    }
    Ok(target)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn systemd_quoting_preserves_literals_and_rejects_line_injection() {
        assert_eq!(
            quote("/a b/$x%q\\\"", true).unwrap(),
            "\"/a b/$$x%%q\\\\\\\"\""
        );
        assert_eq!(quote("KEY=$x%q", false).unwrap(), "\"KEY=$x%%q\"");
        assert!(quote("x\nExecStart=evil", true).is_err());
    }
}
